[project]
name = "demodulador"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bladerf",
    "matplotlib>=3.10.8",
    "numba>=0.65.1",
    "numpy<2.0",
    "pandas<3.0",
    "pyqt6>=6.11.0",
    "pyqtgraph>=0.14.0",
    "pyrtlsdr==0.2.93",
    "python-hackrf<=1.4.0",
    "pyusb>=1.3.1",
    "scipy>=1.17.1",
    "setuptools<69.0.0",
    "sounddevice>=0.5.5",
    "usb>=0.0.83.dev0",
]

[tool.uv.sources]
bladerf = { git = "https://github.com/Nuand/bladeRF.git", subdirectory = "host/libraries/libbladeRF_bindings/python" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
